# Project
version = 2.0.14
group = de.draradech.simplefog
java_version = 25

# Common
mod_author = Draradech
mod_name = Simple Fog Control
mod_id = simplefog

# Minecraft
minecraft_version = 26.2

# NeoForm https://projects.neoforged.net/neoforged/neoform
neo_form_version = 26.2-1

# Fabric https://fabricmc.net/develop/
fabric_loader_version = 0.19.3

# NeoForge https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 26.2.0.6-beta

# Dependencies
clothconfig_version = 26.2.155
modmenu_version = 20.0.0-beta.3

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
